package com.lou.infinitechatagent.chat;

import com.lou.infinitechatagent.config.RagJdbcConfig;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.Resource;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class ChatHistorySchemaInitializer {

    @Resource
    private JdbcTemplate ragJdbcTemplate;

    @PostConstruct
    public void init() {
        if (RagJdbcConfig.isH2(ragJdbcTemplate)) {
            initH2();
            return;
        }
        initMysql();
    }

    private void initMysql() {
        ragJdbcTemplate.execute("""
                create table if not exists chat_session (
                    id bigint primary key auto_increment,
                    user_id bigint not null,
                    session_id bigint not null,
                    title varchar(255) not null,
                    mode varchar(64) not null,
                    summary text null,
                    turn_count int not null default 0,
                    last_status varchar(32) null,
                    last_message_at datetime null,
                    created_at datetime not null default current_timestamp,
                    updated_at datetime not null default current_timestamp on update current_timestamp,
                    unique key uk_chat_session_user_session (user_id, session_id),
                    key idx_chat_session_user_updated (user_id, updated_at)
                ) engine=InnoDB default charset=utf8mb4
                """);
        ragJdbcTemplate.execute("""
                create table if not exists chat_turn (
                    id bigint primary key auto_increment,
                    user_id bigint not null,
                    session_id bigint not null,
                    mode varchar(64) not null,
                    prompt text not null,
                    answer text null,
                    status varchar(32) not null,
                    request_id varchar(128) null,
                    mini_summary varchar(512) not null,
                    error_message text null,
                    metadata_json text null,
                    created_at datetime not null default current_timestamp,
                    key idx_chat_turn_user_session_created (user_id, session_id, created_at),
                    key idx_chat_turn_request_id (request_id)
                ) engine=InnoDB default charset=utf8mb4
                """);
        log.info("Chat History - MySQL schema ready");
    }

    private void initH2() {
        ragJdbcTemplate.execute("""
                create table if not exists chat_session (
                    id bigint generated by default as identity primary key,
                    user_id bigint not null,
                    session_id bigint not null,
                    title varchar(255) not null,
                    mode varchar(64) not null,
                    summary clob null,
                    turn_count int not null default 0,
                    last_status varchar(32) null,
                    last_message_at timestamp null,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp,
                    constraint uk_chat_session_user_session unique (user_id, session_id)
                )
                """);
        ragJdbcTemplate.execute("""
                create table if not exists chat_turn (
                    id bigint generated by default as identity primary key,
                    user_id bigint not null,
                    session_id bigint not null,
                    mode varchar(64) not null,
                    prompt clob not null,
                    answer clob null,
                    status varchar(32) not null,
                    request_id varchar(128) null,
                    mini_summary varchar(512) not null,
                    error_message clob null,
                    metadata_json clob null,
                    created_at timestamp not null default current_timestamp
                )
                """);
        RagJdbcConfig.createIndexIfMissing(ragJdbcTemplate, "chat_session", "idx_chat_session_user_updated", "user_id, updated_at");
        RagJdbcConfig.createIndexIfMissing(ragJdbcTemplate, "chat_turn", "idx_chat_turn_user_session_created", "user_id, session_id, created_at");
        RagJdbcConfig.createIndexIfMissing(ragJdbcTemplate, "chat_turn", "idx_chat_turn_request_id", "request_id");
        log.info("Chat History - H2 schema ready");
    }
}
